POST http://localhost:4002/customers
Content-Type: application/json
Accept: application/json

{
  "name": "testing logistics",
  "email": "logisticstest@gmail.com",
    "address": "456 Commerce Blvd"
}