POST http://localhost:4000/api/orders
Authorization: Bearer {{token}}
Content-Type: Application/json

{
  "customerId": "f1c1951f-831a-4e3a-94bb-c33d6bf47bd2",
  "product": "Luxury soap",
    "quantity": "1",
    "price": "20000000"
}