POST http://localhost:4003/orders
Content-Type: Application/json

{
  "customerId": "1b95646d-5d2d-44ee-876c-9628547950ac",
  "product": "Laptop-Model-Y",
    "quantity": "1",
    "price": "2000000"
}